### ISSUE TITLE
How do I feeding page change events into the selected fragment?

### ISSUE THREAD

**Issue by ishan1608** [Pixplicity/MultiViewPager#13]
I am trying to make all the icons white except the currently selected one which will be blue.
I am trying to do this using onPageChangeListener.
I have added 8 Fragments and my PagerAdapter reflects the same but when I am accessing the childCount of MultiViewPager itself, it only shows 6 and crashes when I swipe my way to the right end of MultiViewPager

I tried getting hold of the fragments and their views using an array in the activity. However it is not giving me irratic behaviour. Some views get regenerated out of nowhere. I can't seem to wrap my head around it. 
Please Help

**Comment by pflammertsma** [comment]
This isn't related to MultiViewPager, but is expected behavior of the support library's ViewPager.

There are a few things you're confused about:
- `childCount` reflects the number of views immediately children of the ViewPager. This is dynamically changed to only contain enough views to display on the screen, which is a memory optimization similar to the behavior of ListViews. It has no immediate relationship with the number of fragments in your ViewPager (except perhaps that it will never exceed that number).
- The lifecycles of your fragments are related to this. Off-screen fragments may be created as they're prepared before being 'selected' (i.e. centered) in the ViewPager. There is no lifecycle event for fragments when they reach the selected state; you need to track this yourself.
- Your approach through [`ViewPager.OnPageChangeListener`](http://developer.android.com/reference/android/support/v4/view/ViewPager.OnPageChangeListener.html) is correct; you should perform some callback from the adapter into the fragment associated with that page index.
