### ISSUE TITLE
How do I set click listeners on pages?

### ISSUE THREAD

**Issue by ishan1608** [Pixplicity/MultiViewPager#14]
I have  a MultiViewPager in my current app, I have total of 8 items and I am displaying around 5 items at a time.
What I am trying to do is to make the item selected when I click on it.
How can I do that ?
I tried setting click listener on the Fragment's view itself passing position to it's constructor, but that is giving me erratic results. I also tried getting hold of all the view's for all the fragments and setting click listener on those, but that is giving me counts up to 5 only.

Please Help, This is an important feature for my app.

**Comment by pflammertsma** [comment]
If you're setting the click listener on the root view of a page, you may be having problems with that approach because the root view is in reality much wider than what's displayed. The reason for this, is that MultiViewPager uses negative margins to compute the overlap of pages.

In the sample, observe that [`activity_pager`](https://github.com/Pixplicity/MultiViewPager/blob/master/sample/src/main/res/layout/activity_pager.xml) informs the MultiViewPager to match children widths to a specific view ID:

```
app:matchChildWidth="@+id/vg_cover"
```

This corresponds with a view defined in [`fragment_page`](https://github.com/Pixplicity/MultiViewPager/blob/master/sample/src/main/res/layout/fragment_page.xml):

```
<RelativeLayout
    android:id="@+id/vg_cover"
    android:layout_width="200dp"
    android:layout_height="match_parent"
    android:layout_centerInParent="true"
    tools:ignore="UselessParent">
```

What you will want to do, is set a click listener on _that_ view, instead of the root view of your fragment.

**Comment by ishan1608** [comment]
Thanks, I was wondering what's going on!
