### ISSUE TITLE
Adding PageTransformer does not work as intended

### ISSUE THREAD

**Issue by akslive** [Pixplicity/MultiViewPager#16]
Hi, 
I needed to add custom animation with MultiViewPager but failed the animation doesn't work properly.

**Comment by pflammertsma** [comment]
Can you try using your animation in a conventional ViewPager first?

If the problem is specifically related to MultiViewPager, please provide a
more detailed description of what you expect to happen, what happens, and
steps to reproduce. A code snippet with your PageTransform would be very
useful in troubleshooting this.
